### ISSUE TITLE
Unfurling support?

### ISSUE THREAD

**Issue by IanVS** [php-slack/slack#28]
Hi, I'm admittedly very new to slack app development, but I am working on an app which will unfurl links to my web application.  The slack docs say to use [chat.unfurl](https://api.slack.com/methods/chat.unfurl), is that something which is supported with this library?  From what I can tell, it doesn't seem like it.  Thanks!

**Comment by alek13** [comment]
Sorry for this lag :)
You can use [`unfurl_links` setting](https://github.com/php-slack/slack#settings)
