### ISSUE TITLE
No way to set response_type to allow public responses in channels

### ISSUE THREAD

**Issue by sparkwatson** [php-slack/slack#33]
I am trying to create a Slash Command that responds publicly from the channel it was invoked.
While this package allows you to respond privately, unless I'm missing it, 
it doesn't support the `response_type = 'in_channel'`
setting required to do so as detailed here:
https://api.slack.com/interactivity/slash-commands#sending_an_immediate_response

**Comment by sparkwatson** [comment]
mocked up a pr to fix here:
https://github.com/php-slack/slack/pull/34

**Comment by alek13** [comment]
fixed by #34
