### ISSUE TITLE
Add support of Slack Blocks Kit

### ISSUE THREAD

**Issue by juherr** [php-slack/slack#37]
According to the doc:

> In early 2019 we introduced a new way of composing messages, by using blocks to create rich layouts and enable interactivity. Slack apps designed and built before then may have used features such as attachments which are now considered outmoded.

https://api.slack.com/messaging/attachments-to-blocks

I will be awesome to have a rich php api that will help to generate it.

**Comment by cmbuckley** [comment]
I had the same need at roughly the same time as this issue was raised.

I’ve started work on this in [cmbuckley/slack@blocks](https://github.com/cmbuckley/slack/tree/blocks), but I’m still a way off submitting a proper PR.
