### ISSUE TITLE
[AttachmentAction] Don't return a null object on 'confirm'

### ISSUE THREAD

**Issue by iNilo** [php-slack/slack#41]
https://github.com/php-slack/slack/blob/dcb918671a203342f7095542d56eb5f519a133d8/src/AttachmentAction.php#L261

by returning a "null" slack will pop a default confirmation window

![slack_2020-03-22_16-16-13](https://user-images.githubusercontent.com/3451587/77253084-83a87a80-6c58-11ea-83a3-ce4fa904595f.png)

If its "null" (no confirmation) the key should not be returned.

**Comment by alek13** [comment]
Hi, @iNilo . Thanks for issue. Can you create PR ?
