### ISSUE TITLE
Sections /w Fields should not have a top level "text" key. Fatal error is generated

### ISSUE THREAD

**Issue by ewartx** [php-slack/slack#48]
src/Block/Section.php line 146

```
$data = [
    'type' => $this->getType(),
    'text' => $this->getText()->toArray();
];
```
 
Suggestion, add a check
```
if ( $this->getText() ) {
       $data['text'] = $this->getText()->toArray();
}
```

**Comment by cmbuckley** [comment]
The text is required when there are no fields, but is optional when fields are present. So a section may have both attributes, but needs to throw an Exception when there are neither.

**Comment by ewartx** [comment]
I see. However, the fatal error was thrown when I had fields present. So something is missing here.

**Comment by cmbuckley** [comment]
Yes, see the link above my comment, #49
