### ISSUE TITLE
Guzzle 7.* support?

### ISSUE THREAD

**Issue by malle-pietje** [php-slack/slack#51]
Thanks for maintaining this package!

Is there a specific reason it doesn't list Guzzle 7 in the composer.json file? I have a project where I would like to include it but another package requires Guzzle 7 which is preventing me from using this Slack package.

**Comment by alek13** [comment]
@malle-pietje Hi.
No, there is not specific reason. But I'm not tested it with Guzzle 7.
If we have no problems, we can add `~7.0|.....`

PR welcome :) (to branch `1.0` & to branch `master`)

**Comment by esetnik** [comment]
@alek13 I have added two PRs for the requested changes.

**Comment by alek13** [comment]
For now have no access to comp to create bump version commit & add tag for version. Will return home in a week

**Comment by paavo** [comment]
What about supporting Guzzle `^7.3`?
