### ISSUE TITLE
Support php 8

### ISSUE THREAD

**Issue by esetnik** [php-slack/slack#57]
I just opened this issue to start the conversation about any issues that come up when running the package in php 8

**Comment by alek13** [comment]
#56

**Comment by phpfui** [comment]
Can we get a PHP 8.0 compatible release?  I think it is ready to go.  Either 1.12.1 or 1.13.0 would work.  Probably 1.12.1 as there are no real code changes, just support files.

Thanks!

**Comment by alek13** [comment]
@phpfui I hope this week I will have time to have a look.
> there are no real code changes, just support files

not quite..
#56 was merged into `master` (ver. [2.x-dev](https://packagist.org/packages/alek13/slack#dev-master)), not into `1.0` branch (ver. [1.x](https://packagist.org/packages/alek13/slack#1.0.x-dev)).
And in `master` we have some new features.

**Comment by esetnik** [comment]
@alek13 just checking in on this. Is there any plans to release the php 8 compatible code?

**Comment by rubenvanassche** [comment]
Any update on this?

**Comment by alek13** [comment]
Support PHP 8.0 in 
https://github.com/php-slack/slack/releases/tag/2.0.0

**Comment by phpfui** [comment]
Nice!  Love the dropping PHP 5 and 7.0 support. Great way to move forward.  Thanks for the PHP 8.0 support.

**Comment by rubenvanassche** [comment]
Thank you @alek13!
