### ISSUE TITLE
README is outdated

### ISSUE THREAD

**Issue by NinoSkopac** [php-slack/slack#58]
This is not how it works anymore, I believe:

<img width="356" alt="Screenshot 2020-12-13 at 08 30 48" src="https://user-images.githubusercontent.com/1783732/102007050-98b0c680-3d1d-11eb-8d65-337b31197b26.png">

it's more like this:

```php
    protected function triggerNotification(string $from, string $messageText): void {
        $client = new Client($this->notificationsHook);
        $message = new Message($client);
        $message->setUsername($from)->setText($messageText);
        $client->sendMessage($message);
    }
```

**Comment by cmbuckley** [comment]
`Client::send` is captured by [`Client::__call`](https://github.com/php-slack/slack/blob/1.12.0/src/Client.php#L140), so `$client->send('Hello world!')` is a shorthand for:

```php
$message = $client->createMessage();
$message->send('Hello world!');
```

Other than the username, those snippets achieve the same thing.

**Comment by NinoSkopac** [comment]
Ah okay.

I used to use Client::send() but have shifted to the new paradigm because my IDE (PHPStorm) was saying the aforementioned method doesn't exist.

**Comment by cmbuckley** [comment]
Ah OK, in master branch these are documented using [`@method properties`](https://github.com/php-slack/slack/blob/master/src/Client.php#L8-L9) which PHPStorm respects — this will be in an upcoming release
