### ISSUE TITLE
Playground link does not work

### ISSUE THREAD

**Issue by C0rn3j** [php-slack/slack#67]
Wanted to figure out how to send `[text](url)` Markdown but found out the playground links in /slack and /playground are both dead 

https://github.com/php-slack/playground

**Comment by alek13** [comment]
which one links ? can you describe in more detail ?

**Comment by C0rn3j** [comment]
https://github.com/php-slack/slack#questions
https://github.com/php-slack/playground#see-the-real-message
The Slack workspace ones.

---

Is the []() Markdown functionality unsupported?

I can open a separate issue for the URL Markdown if needed.

```
$message .= "[".rtrim($commit->message)."](".$commit->url.") by _".$commit->author->name."_";
```
![image](https://user-images.githubusercontent.com/1641362/132217984-fe06dbda-74c9-4c05-b594-3326b1f61641.png)

**Comment by cmbuckley** [comment]
The `<|>` mrkdwn (not Markdown) functionality is what you want ([more info here](https://api.slack.com/reference/surfaces/formatting#linking-urls)) but be aware it's the other way around from markdown, i.e. `<url|text>` instead of `[text](url)`.

```php
$url = 'https://api.slack.com/reference/surfaces/formatting#linking-urls';
$client->send("Please see <$url|Formatting text for app surfaces> :smile:");
```

**Comment by C0rn3j** [comment]
The `<url|text>` syntax works great, thanks!

**Comment by alek13** [comment]
@C0rn3j thnx. We fix this links
